#pragma once

namespace festation
{
    static constexpr const uint32_t PHYSICAL_MEMORY_MASK = 0x1FFFFFFF; // 0.5GB per region in MIPS 32 bits

    constexpr size_t MAIN_RAM_SIZE = 0x200000;               // 2MB
    constexpr size_t MAIN_RAM_EXTENDED_SIZE = 0x800000;      // 8MB (mirrors every 2MB)
    constexpr size_t EXPANSION_REGION1_SIZE = 0x800000;      // 8MB
    constexpr size_t SCRATCHPAD_SIZE = 0x400;                // 1KB
    constexpr size_t IO_PORTS_SIZE = 0x1000;                 // 4KB
    constexpr size_t EXPANSION_REGION2_SIZE = 0x2000;        // 8KB
    constexpr size_t EXPANSION_REGION3_SIZE = 0x200000;      // 2MB
    constexpr size_t BIOS_ROM_SIZE = 0x80000;                // 512KB
    constexpr size_t CACHE_CONTROL_SIZE = 0x200;             // 0.5KB

    enum MemoryMapRangesSizeMasks        
    {
        MAIN_RAM_SIZE_MASK = 0x1FFFFF,
        MAIN_RAM_EXTENDED_SIZE_MASK = 0x7FFFFF,
        EXPANSION_REGION1_SIZE_MASK = 0x7FFFFF,
        SCRATCHPAD_SIZE_MASK = 0x3FF,
        IO_PORTS_SIZE_MASK = 0xFFF,
        EXPANSION_REGION2_SIZE_MASK = 0x1FFF,
        EXPANSION_REGION3_SIZE_MASK = 0x1FFFFF,
        BIOS_ROM_SIZE_MASK = 0x7FFFF,
        CACHE_CONTROL_SIZE_MASK = 0x1FF
    };

    enum MemoryMapRegions
    {
        MAIN_RAM_START = 0x00000000,
        MAIN_RAM_END = MAIN_RAM_START + MAIN_RAM_EXTENDED_SIZE_MASK,
        EXPANSION_REGION1_START = 0x1F000000,
        EXPANSION_REGION1_END = EXPANSION_REGION1_START + EXPANSION_REGION1_SIZE_MASK,
        SCRATCHPAD_START = 0x1F800000,
        SCRATCHPAD_END = SCRATCHPAD_START + SCRATCHPAD_SIZE_MASK,
        IO_PORTS_START = 0x1F801000,
        IO_PORTS_END = IO_PORTS_START + IO_PORTS_SIZE_MASK,
        EXPANSION_REGION2_START = 0x1F802000,
        EXPANSION_REGION2_END = EXPANSION_REGION2_START + EXPANSION_REGION2_SIZE_MASK,
        EXPANSION_REGION3_START = 0x1FA00000,
        EXPANSION_REGION3_END = EXPANSION_REGION3_START + EXPANSION_REGION3_SIZE_MASK,
        BIOS_ROM_START = 0x1FC00000,
        BIOS_ROM_END = BIOS_ROM_START + BIOS_ROM_SIZE_MASK,
        CACHE_CONTROL_START = 0xFFFE0000,
        CACHE_CONTROL_END = CACHE_CONTROL_START + CACHE_CONTROL_SIZE_MASK
    };
};